name: devex_hosted_control_plane
version: 0.1.0-dev
publish_to: none
resolution: workspace

environment:
  sdk: ^3.12.0

dependencies:
  crypto: ^3.0.6
  devex_contracts: ^0.1.0-dev
  devex_engine: ^0.1.0-dev
  devex_runtime: ^0.1.0-dev
  jose: ^0.3.5+2
  opentelemetry: ^0.18.11
  postgres: ^3.5.12
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  shelf_web_socket: ^3.0.0
  web_socket_channel: ^3.0.3

dev_dependencies:
  test: ^1.26.3
