apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "control-plane.name" . }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "control-plane.selectorLabels" . | nindent 6 }}
