apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "control-plane.name" . }}
  labels:
    {{- include "control-plane.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
automountServiceAccountToken: false
