name: workspace_host
publish_to: none
resolution: workspace

environment:
  sdk: ^3.12.0

dependencies:
  execution_runtime: ^0.1.0-dev
  experience_contracts: ^0.1.0-dev

dev_dependencies:
  test: ^1.26.3
