apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "devex-hosted.name" . }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "devex-hosted.selectorLabels" . | nindent 6 }}
