{{- if .Values.remote.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "devex-hosted.remoteRoleName" . }}
  labels:
    {{- include "devex-hosted.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["create", "get", "delete"]
  - apiGroups: [""]
    resources: ["serviceaccounts", "secrets", "configmaps", "services"]
    verbs: ["create"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["networkpolicies"]
    verbs: ["create"]
  - apiGroups: ["gateway.networking.k8s.io"]
    resources: ["httproutes"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "devex-hosted.remoteRoleName" . }}
  labels:
    {{- include "devex-hosted.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "devex-hosted.remoteRoleName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "devex-hosted.name" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
