apiVersion: v1
kind: Service
metadata:
  name: {{ include "devex-hosted.name" . }}
  labels:
    {{- include "devex-hosted.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "devex-hosted.selectorLabels" . | nindent 4 }}
  ports:
    - {name: http, port: {{ .Values.service.port }}, targetPort: http, protocol: TCP}
