apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "devex-hosted.name" . }}
  labels:
    {{- include "devex-hosted.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
automountServiceAccountToken: false
