name: devex_preview
version: 0.1.0-dev
resolution: workspace

environment:
  sdk: ^3.12.0

dependencies:
  devex_contracts: ^0.1.0-dev
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
