name: devex_testkit
version: 0.1.0-dev
resolution: workspace

environment:
  sdk: ^3.12.0

dependencies:
  devex_contracts: ^0.1.0-dev
  devex_engine: ^0.1.0-dev
  devex_runtime: ^0.1.0-dev

dev_dependencies:
  test: ^1.26.3
